version: '3'
services:
  jekyll:
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../src/.:/app
    command: >
      bash -c "
        bundle install --path vendor/bundle
        bundle exec jekyll serve --no-watch --force_polling --incremental --trace --host=0.0.0.0
        "
    tty: true
