version: '3'
services:
  jekyll:
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../src/.:/app
    command: bundle install --path vendor/bundle && bundle exec jekyll serve --force_polling --host --incremental --trace --no-watch
    tty: true
